---
- name: Set Git global user email
  community.general.git_config:
    name: user.email
    scope: global
    value: "felix.mathias95@gmail.com"

- name: Set Git global user name
  community.general.git_config:
    name: user.name
    scope: global
    value: "Mathod"

- name: S'assurer que le dossier /home/mathod/github existe
  ansible.builtin.file:
    path: /home/mathod/github
    state: directory
    owner: mathod
    group: mathod
    mode: '0755'

- name: Cloner les dépôts Git
  ansible.builtin.git:
    repo: "{{ item }}"
    dest: "/home/mathod/github/{{ item | basename }}"
    clone: yes
    update: yes
    version: HEAD
  loop:
    - https://github.com/Mathod95/apps
    - https://github.com/Mathod95/wsl
    - https://github.com/Mathod95/argocd-autopilot
    - https://github.com/Mathod95/courses
  become_user: mathod