---
- name: Disable Homebrew analytics
  ansible.builtin.command:
    cmd: /home/linuxbrew/.linuxbrew/bin/brew analytics off
  register: brew_analytics_result
  changed_when: false

# Install from zplug ?
#- name: Tap olets/tap
#  community.general.homebrew_tap:
#    name: olets/tap
#    state: present

# Check package to install !
- name: Install {{ item }} via Homebrew
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - zsh
    - zplug

- name: Ajouter zsh Shell à la liste des shells valides
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: "/home/linuxbrew/.linuxbrew/bin/zsh"
    create: yes
  become: true

#- name: Changer le shell par défaut avec chsh
#  ansible.builtin.shell: chsh -s /home/linuxbrew/.linuxbrew/bin/zsh {{ ansible_env.USER }}
#  become: true

- name: Change default shell to zsh if it's not already set
  ansible.builtin.shell: |
    current_shell=$(getent passwd {{ ansible_env.USER }} | cut -d: -f7)
    if [ "$current_shell" != "/home/linuxbrew/.linuxbrew/bin/zsh" ]; then
      chsh -s /home/linuxbrew/.linuxbrew/bin/zsh {{ ansible_env.USER }}
    fi
  become: true
  register: result
  changed_when: "'chsh' in result.stdout"  # Only mark as changed if the output contains "chsh"

- name: Copy .zshrc
  ansible.builtin.copy:
    src: .zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"
    mode: '0644'

#- name: Copy .zshrc
#  ansible.builtin.copy:
#    src: .histfile
#    dest: "{{ ansible_env.HOME }}/.histfile"
#    mode: '0600'
#
#- name: Ensure ~/config/zsh-abbr directory exists with correct permissions
#  ansible.builtin.file:
#    path: "{{ ansible_env.HOME }}/.config/zsh-abbr"
#    state: directory
#    mode: '0755'
#
#- name: Copy user-abbreviations
#  ansible.builtin.copy:
#    src: user-abbreviations
#    dest: "{{ ansible_env.HOME }}/.config/zsh-abbr/user-abbreviations"
#    mode: '0600'
#
#- name: Ensure ~/config/zellij directory exists with correct permissions
#  ansible.builtin.file:
#    path: "{{ ansible_env.HOME }}/.config/zellij"
#    state: directory
#    mode: '0755'
#
#- name: Copy config.kdl
#  ansible.builtin.copy:
#    src: config.kdl
#    dest: "{{ ansible_env.HOME }}/.config/zellij/config.kdl"
#    mode: '0644'