---
- name: Ajouter zsh Shell à la liste des shells valides
  ansible.builtin.lineinfile:
    path: /etc/shells
    line: "/home/linuxbrew/.linuxbrew/bin/zsh"
    create: yes
  become: true

- name: Changer le shell par défaut avec chsh
  ansible.builtin.shell: chsh -s /home/linuxbrew/.linuxbrew/bin/zsh {{ ansible_env.USER }}
  become: true

- name: Copy .zshrc
  ansible.builtin.copy:
    src: .zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"
    mode: '0644'

- name: Copy .zshrc
  ansible.builtin.copy:
    src: .histfile
    dest: "{{ ansible_env.HOME }}/.histfile"
    mode: '0600'

- name: Ensure ~/config/zsh-abbr directory exists with correct permissions
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/zsh-abbr"
    state: directory
    mode: '0755'

- name: Copy user-abbreviations
  ansible.builtin.copy:
    src: user-abbreviations
    dest: "{{ ansible_env.HOME }}/.config/zsh-abbr/user-abbreviations"
    mode: '0600'

- name: Ensure ~/config/zellij directory exists with correct permissions
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.config/zellij"
    state: directory
    mode: '0755'

- name: Copy config.kdl
  ansible.builtin.copy:
    src: config.kdl
    dest: "{{ ansible_env.HOME }}/.config/zellij/config.kdl"
    mode: '0644'