---
- name: Create keyrings directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/debian/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  become: true

- name: Add Docker APT repository
  ansible.builtin.copy:
    content: |
      deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    dest: /etc/apt/sources.list.d/docker.list
    mode: '0644'
  become: true

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: yes
  become: true

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      #- docker-buildx-plugin
      #- docker-compose-plugin
    state: present
  become: true

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes
  become: true

- name: Add user to journalctl group
  ansible.builtin.user:
    name: "{{ ansible_env.USER }}"
    groups: systemd-journal
    append: yes
  become: true

- name: Check current groups of the user
  ansible.builtin.command: id -Gn "{{ ansible_env.USER }}"
  register: user_groups
  changed_when: false