---
- name: Configure WSL
  hosts: localhost
  connection: local
  gather_facts: yes
  become: false

  roles:
    - role: ssh
    - role: github
    #- role: docker
    #- role: brewPackages
    #- role: vscode
    #- role: zsh